name: verbal_expressions
description: A package that helps to construct difficult regular expressions.
version: 1.0.0-nullsafety
author: Ne4istb <anechytailov@gmail.com>, sergiolisan <sergiolisan@gmail.com>
homepage: https://github.com/VerbalExpressions/DartVerbalExpressions

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.3
